AllCops:
  TargetRubyVersion: 2.4

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - ap
    - gem
    - puts
    - raise
    - require
    - source
    - yield
