{{- if .Values.rbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registry-cleaner
  {{- template "standard-labels" . }}
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - pods
      - replicationcontrollers
    verbs: ["get", "list"]
  - apiGroups: ["apps", "extensions"]
    verbs: ["get", "list"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
  - apiGroups: ["batch"]
    verbs: ["get", "list"]
    resources:
      - cronjobs
{{- end }}
